### ISSUE TITLE
Post title length checks

### ISSUE THREAD

**Issue by el1t** [elmzteam/bydesign#10]
should be > zero and maybe use ellipses to prevent multiple line overflow
edit: removed extra issues

**Comment by el1t** [comment]
Also [this line](https://github.com/elmzteam/bydesign/blob/1df95645efb35a4eb3d98ee1a719c024bfeb6a2e/server/renderer.js#L157) should probably be moved outside the for-loop to avoid creating tons of regex objects, and same for [this](https://github.com/elmzteam/bydesign/blob/1df95645efb35a4eb3d98ee1a719c024bfeb6a2e/server/renderer.js#L164)

**Comment by bluepichu** [comment]
If you have six issues, please make six issues.

**Comment by bluepichu** [comment]
But on the subject of this particular post... I don't think that this is required.  In fact, I'm not sure that the tag length check should be forced either.  I'm inclined to blame the content creator if they decide do do something dumb like paste the entire post in the title box.

**Comment by bluepichu** [comment]
On the other hand, prohibiting zero-length titles seems reasonable.

**Comment by bluepichu** [comment]
What's the state of this after #87?  Do we care?

**Comment by zwade** [comment]
My vote is no, but tbh I care less about policy enforcement for admins

**Comment by bluepichu** [comment]
I think we can agree to drop this, since an empty title is user error.  Closing.
