### ISSUE TITLE
Make HOME ABOUT ARCHIVE CONTACT do something

### ISSUE THREAD

**Issue by zwade** [elmzteam/bydesign#18]
Should be pretty simple

**Comment by bluepichu** [comment]
First things first... what header links do we actually WANT?  "Home" and "About" are pretty reasonable.  The front page is already an archive so that's a bit silly.  "Contact" or "Authors" would probably be good for a breakdown of each individual.

**Comment by zwade** [comment]
I maintain that search would make a good fourth

**Comment by bluepichu** [comment]
There should probably just be a search input - no need to go to a page to do a search.

**Comment by el1t** [comment]
A button to login/goto admin interface would be great
