### ISSUE TITLE
Add delete button to admin/editor views

### ISSUE THREAD

**Issue by el1t** [elmzteam/bydesign#23]

**Comment by zwade** [comment]
@el1t check if this satisfies it

**Comment by el1t** [comment]
I was thinking of a true delete button, to get rid of accidental posts. Otherwise it would just stay there forever

**Comment by bluepichu** [comment]
@el1t do you plan on implementing, or should I reassign?

**Comment by el1t** [comment]
Oh right didn't we decide not to have legit delete buttons? In that case we can close this

**Comment by bluepichu** [comment]
I personally think we should - with at least two levels of confirmation on the client - but we could pass on this for now if we don't see it as important.

**Comment by el1t** [comment]
Would the privilege be restricted to the author of the post? Perhaps also require that the post is empty? Deletion would be less necessary with adjustable post dates, I think.

**Comment by bluepichu** [comment]
Requiring an empty post is actually a good requirement.  In fact, we could just auto-delete posts that are totally empty (no title, no content, no tags), and that'd probably be sufficient.

**Comment by el1t** [comment]
Yeah at that point the post's as good as gone eh

**Comment by zwade** [comment]
Ooh good idea, I can see about adding in that logic
