### ISSUE TITLE
Fix mobile support

### ISSUE THREAD

**Issue by el1t** [elmzteam/bydesign#39]
- [x] Main pages
- [ ] Admin panel
- [ ] Post editor

**Comment by zwade** [comment]
Admin and editor not complete, but all forward facing pages are

**Comment by bluepichu** [comment]
It looks like the big problem here is with using `rem` units to size things.  It's a good idea in theory, but it seems to be acting not so well in practice.

**Comment by bluepichu** [comment]
I take that back.  The SCSS for the admin pages on mobile just generally doesn't make sense at all.  The use of `rem` is fine.
