### ISSUE TITLE
Chrome on Mac?

### ISSUE THREAD

**Issue by KyleHerndon** [elmzteam/bydesign#45]
A user on Mac/Chrome found that the author box would not flush right.

**Comment by bluepichu** [comment]
Could we get more information/version numbers on both the OS and Chrome?  I use Chrome 47 on OSX 10.10.5 and couldn't reproduce it.

<img width="1280" alt="screenshot 2016-01-21 15 16 40" src="https://cloud.githubusercontent.com/assets/1878074/12494338/91ce6dba-c057-11e5-9706-d56f13d59632.png">

**Comment by KyleHerndon** [comment]
Chrome Version 47.0.2526.111 (64-bit)
Mac OS 10.11.2

**Comment by bluepichu** [comment]
Could you get a screenshot of the issue?  I'd really prefer not to El Capitan myself.  Also, I just got a Chrome update (to Chrome 48) on my mac, so that may or may not fix the problem.

**Comment by KyleHerndon** [comment]
![image](https://cloud.githubusercontent.com/assets/5266607/12496417/417b5ea0-c05b-11e5-92a3-8c97e76b38a6.png)
![image](https://cloud.githubusercontent.com/assets/5266607/12496433/552e1320-c05b-11e5-873a-66116f31343c.png)

**Comment by bluepichu** [comment]
Still Chrome 47, or updated to 48?

**Comment by bluepichu** [comment]
(Also, is this your computer, or someone else's?)

**Comment by KyleHerndon** [comment]
Someone else's. I also asked if he had any extensions, and he said only ad block.

I had an independent UX designer audit the website :P

**Comment by bluepichu** [comment]
Is this still broken circa Chrome 50?

**Comment by KyleHerndon** [comment]
I'll message him now.

**Comment by KyleHerndon** [comment]
He is no longer getting the issue. I think we can mark this as resolved.
