### ISSUE TITLE
Tag filtering

### ISSUE THREAD

**Issue by dhlanm** [elmzteam/bydesign#7]
Tags need to be filtered to only accept legal tags.

**Comment by bluepichu** [comment]
I think the first question is what a legal tag is.

**Comment by dhlanm** [comment]
Well, some sort of length limit seems to be in order

**Comment by dhlanm** [comment]
Also, Zach wants lowercase only (just convert tags to lower case?) 
Probably filter out most fancy unicode characters too unless you _want_ to go through the hassle of supporting them.

**Comment by bluepichu** [comment]
We could probably just regex this.  Maybe `[a-z][a-z0-9-]{,11}`?  Do you think we'll need more characters available?

**Comment by zwade** [comment]
Oh didn't realize there was a thread, I am matching on [a-z0-9]{0,16} . Is this cool?

**Comment by zwade** [comment]
(JS doesn't support {,m} syntax)

**Comment by zwade** [comment]
fixed by 9df3cfae5fc50f7

**Comment by el1t** [comment]
(fwiw can close the issue via commit e.g. `[Fixes #7] Add tag regex`)
