### ISSUE TITLE
Regarding titles

### ISSUE THREAD

**Issue by bluepichu** [elmzteam/bydesign#74]
The fact that they match the articles is good, but I think they could use more work.

Here's what I'd do:

| Location | Title |
| --- | --- |
| `/` | Down to the Wire |
| `/tags/{tagname}` | Posts tagged {tagname} &mdash; Down to the Wire |
| `/author/{authorname}` | Posts by {authorname} &mdash; Down to the Wire |
| `/posts/{timestamp}` | {articlename} &mdash; Down to the Wire |
| `/admin` | Admin Panel &mdash; Down to the Wire |
| `/editor/{timestamp}` | Editing "{articlename}" &mdash; Down to the Wire |
| `/preview/{timestamp}` | {articlename} (Preview) &mdash; Down to the Wire |

Thoughts?

(Edited: fixed formatting, added missing preview page)

**Comment by zwade** [comment]
I agree that they could be fleshed out more, but you don't want titles very long. At the very least, I think that there should be some indication that the page is from dttw when you glance at the tag. Maybe favicon is sufficient for this, but i'm not sure

**Comment by bluepichu** [comment]
I know I personally rely on Favicons to identify what site a tab is on, and it'd be more helpful to get page information via the title.

For example, suppose I can see the favicon and the first six characters of the title for all of my open tabs.  If I have two DttW tabs open to different pages (for example, one editing and one previewing), then if the article title is listed first, I can identify which one is which, but if it's the site title, I can't.

**Comment by bluepichu** [comment]
...reassigning to @zwade because I have no idea what any of the variables in the page render object are.

**Comment by zwade** [comment]
lolk, this is kinda low priority rn tho

**Comment by bluepichu** [comment]
Here's what I got to:

```
<title>{{#if admin}}Admin &mdash; {{/if}}{{#if single}}{{postinf.title.text}} &mdash; {{/if}}Down to the Wire</title>
```

I tried to add `/author/.*` paths but gave up because the object schema got too wacky.

**Comment by zwade** [comment]
Yeah, it's a bit hacky still, from a couple different reorgs. I'm not inclined to clean it up yet, I think that will end up being part of the abstraction code.
