### ISSUE TITLE
Spaces in filename break codeblock rendering

### ISSUE THREAD

**Issue by zwade** [elmzteam/bydesign#76]
so like

``````
```python{File 1}
print 'boo'
`` `
``````

will break

**Comment by bluepichu** [comment]
Whitespace ends the "information" section of the code block, which contains the language.  We'll have to patch around this to get spaces in file names to work.

**Comment by bluepichu** [comment]
Just kidding, I guess I'm a compulsive liar.  Fix wasn't too bad.
