### ISSUE TITLE
Replace <more> with something else

### ISSUE THREAD

**Issue by bluepichu** [elmzteam/bydesign#84]
In particular, because the output has a `<more>` tag wrapping most of the article.

My recommendation is three or more consecutive carets to denote the break.  Conflicts can be handled by using HTML escapes.

**Comment by bluepichu** [comment]
I'll take your silence as agreement and tackle this one later.

**Comment by zwade** [comment]
lol yeah that sounds good. Although in fairness, I was kept meaning to replace it with `<more/>` so you wouldn't have that issue, but `/^^^^*/` is fine too

**Comment by bluepichu** [comment]
What about `/\^{3,}/`?  :)

And also, the way that custom tags are handled, that doesn't actually solve the problem.  You actually CAN'T have a single-tag version of most elements, only those allowed by the HTML spec.

**Comment by zwade** [comment]
I didn't actually realize you couldn't have custom void elements, but ok
