### ISSUE TITLE
Move post data to mongo instead of filestore

### ISSUE THREAD

**Issue by zwade** [elmzteam/bydesign#91]
Addresses comments made in #19

**Comment by addtheletters** [comment]
idk how I feel about this, having posts accessible as files seems more fitting than stuffing them in mongo. The searchability would be nice tho. I think I'd feel better with mirroring than pure db for posts

**Comment by zwade** [comment]
I'm thinking about doing this coupled with an automatic backup daemon. That way even if mongo barfs on us, it's not the end of the world. @bluepichu ?

**Comment by bluepichu** [comment]
I don't see any reason to backup to individual post files - I would think a weekly (or so) full DB backup would be sufficient and reasonable.

**Comment by zwade** [comment]
lol yeah, that's what I was referring to

**Comment by bluepichu** [comment]
Cool.  Just wanted to make sure we were differentiating "backing up the posts" and "backing up the DB", because at least to me those mean different (but related) things.

**Comment by bluepichu** [comment]
See #106 for PR.
